name: Build and push containers

on:
  release:
    types: [published]
  pull_request:

jobs:
  release-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.CONTAINER_USERNAME }}
    steps:
      - name: Compile tag list
        id: tags
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          PREFIX=ghcr.io/laminas/laminas-continuous-integration
          MAJOR="${PREFIX}:$(echo ${TAG} | cut -d. -f1)"
          MINOR="${MAJOR}.$(echo ${TAG} | cut -d. -f2)"
          PATCH="${PREFIX}:${TAG}"
          echo "::set-output name=tags::[\"${MAJOR}\",\"${MINOR}\",\"${PATCH}\"]"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image. Push for release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # target: multi-stage build target name
          pull: true
          push: ${{ github.event_name == 'release' }}
          tags: ${{ join(fromJSON(steps.tags.outputs.tags), ',') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
