name: Build and push containers

on:
  release:
    types: [published]
  pull_request:

jobs:
  release-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.CONTAINER_USERNAME }}
    steps:
      - name: Compile tag list
        id: tags
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          PREFIX=ghcr.io/laminas/laminas-continuous-integration
          MAJOR="${PREFIX}:$(echo ${TAG} | cut -d. -f1)"
          MINOR="${MAJOR}.$(echo ${TAG} | cut -d. -f2)"
          PATCH="${PREFIX}:${TAG}"
          echo "::set-output name=tags::[\"${MAJOR}\",\"${MINOR}\",\"${PATCH}\"]"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ env.DOCKER_USER }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.CONTAINER_PAT }}

      - name: Build and push for release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          tags: ${{ join(fromJSON(steps.tags.outputs.tags), ',') }}
          cache-from: type=registry,ref=ghcr.io/laminas/laminas-continuous-integration-action:build-cache
          cache-to: type=registry,ref=ghcr.io/laminas/laminas-continuous-integration-action:build-cache,mode=max

      - name: Build for local pull request
        if: ${{ github.event_name == 'pull_request' && env.DOCKER_USER }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          pull: true
          push: false
          cache-from: type=registry,ref=ghcr.io/laminas/laminas-continuous-integration-action:build-cache
          cache-to: type=registry,ref=ghcr.io/laminas/laminas-continuous-integration-action:build-cache,mode=max

      - name: Build for fork pull request
        if: ${{ github.event_name == 'pull_request' && ! env.DOCKER_USER }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          pull: true
          push: false
          cache-from: type=registry,ref=ghcr.io/laminas/laminas-continuous-integration-action:build-cache
